// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: claritas.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_claritas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_claritas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_claritas_proto_rawDescGZIP(), []int{0}
}

type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_claritas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_claritas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_claritas_proto_rawDescGZIP(), []int{1}
}

func (x *HealthStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_claritas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_claritas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_claritas_proto_rawDescGZIP(), []int{2}
}

func (x *FileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type HeadersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadersResponse) Reset() {
	*x = HeadersResponse{}
	mi := &file_claritas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadersResponse) ProtoMessage() {}

func (x *HeadersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_claritas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadersResponse.ProtoReflect.Descriptor instead.
func (*HeadersResponse) Descriptor() ([]byte, []int) {
	return file_claritas_proto_rawDescGZIP(), []int{3}
}

func (x *HeadersResponse) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *HeadersResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	XColumn       string                 `protobuf:"bytes,2,opt,name=x_column,json=xColumn,proto3" json:"x_column,omitempty"`
	YColumn       string                 `protobuf:"bytes,3,opt,name=y_column,json=yColumn,proto3" json:"y_column,omitempty"`
	ChunkSize     int32                  `protobuf:"varint,4,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_claritas_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_claritas_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_claritas_proto_rawDescGZIP(), []int{4}
}

func (x *ParseRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ParseRequest) GetXColumn() string {
	if x != nil {
		return x.XColumn
	}
	return ""
}

func (x *ParseRequest) GetYColumn() string {
	if x != nil {
		return x.YColumn
	}
	return ""
}

func (x *ParseRequest) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

type DataChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XNumValues    []float64              `protobuf:"fixed64,1,rep,packed,name=x_num_values,json=xNumValues,proto3" json:"x_num_values,omitempty"`
	YNumValues    []float64              `protobuf:"fixed64,2,rep,packed,name=y_num_values,json=yNumValues,proto3" json:"y_num_values,omitempty"`
	XStringValues []string               `protobuf:"bytes,3,rep,name=x_string_values,json=xStringValues,proto3" json:"x_string_values,omitempty"`
	YStringValues []string               `protobuf:"bytes,4,rep,name=y_string_values,json=yStringValues,proto3" json:"y_string_values,omitempty"`
	XIsString     bool                   `protobuf:"varint,5,opt,name=x_is_string,json=xIsString,proto3" json:"x_is_string,omitempty"`
	YIsString     bool                   `protobuf:"varint,6,opt,name=y_is_string,json=yIsString,proto3" json:"y_is_string,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataChunk) Reset() {
	*x = DataChunk{}
	mi := &file_claritas_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChunk) ProtoMessage() {}

func (x *DataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_claritas_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChunk.ProtoReflect.Descriptor instead.
func (*DataChunk) Descriptor() ([]byte, []int) {
	return file_claritas_proto_rawDescGZIP(), []int{5}
}

func (x *DataChunk) GetXNumValues() []float64 {
	if x != nil {
		return x.XNumValues
	}
	return nil
}

func (x *DataChunk) GetYNumValues() []float64 {
	if x != nil {
		return x.YNumValues
	}
	return nil
}

func (x *DataChunk) GetXStringValues() []string {
	if x != nil {
		return x.XStringValues
	}
	return nil
}

func (x *DataChunk) GetYStringValues() []string {
	if x != nil {
		return x.YStringValues
	}
	return nil
}

func (x *DataChunk) GetXIsString() bool {
	if x != nil {
		return x.XIsString
	}
	return false
}

func (x *DataChunk) GetYIsString() bool {
	if x != nil {
		return x.YIsString
	}
	return false
}

func (x *DataChunk) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_claritas_proto protoreflect.FileDescriptor

const file_claritas_proto_rawDesc = "" +
	"\n" +
	"\x0eclaritas.proto\x12\bclaritas\"\a\n" +
	"\x05Empty\"&\n" +
	"\fHealthStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"*\n" +
	"\vFileRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"P\n" +
	"\x0fHeadersResponse\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x80\x01\n" +
	"\fParseRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x19\n" +
	"\bx_column\x18\x02 \x01(\tR\axColumn\x12\x19\n" +
	"\by_column\x18\x03 \x01(\tR\ayColumn\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x04 \x01(\x05R\tchunkSize\"\x84\x02\n" +
	"\tDataChunk\x12 \n" +
	"\fx_num_values\x18\x01 \x03(\x01R\n" +
	"xNumValues\x12 \n" +
	"\fy_num_values\x18\x02 \x03(\x01R\n" +
	"yNumValues\x12&\n" +
	"\x0fx_string_values\x18\x03 \x03(\tR\rxStringValues\x12&\n" +
	"\x0fy_string_values\x18\x04 \x03(\tR\ryStringValues\x12\x1e\n" +
	"\vx_is_string\x18\x05 \x01(\bR\txIsString\x12\x1e\n" +
	"\vy_is_string\x18\x06 \x01(\bR\tyIsString\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage2\xbe\x01\n" +
	"\x0eClaritasEngine\x12/\n" +
	"\x04Ping\x12\x0f.claritas.Empty\x1a\x16.claritas.HealthStatus\x12>\n" +
	"\n" +
	"GetHeaders\x12\x15.claritas.FileRequest\x1a\x19.claritas.HeadersResponse\x12;\n" +
	"\n" +
	"StreamData\x12\x16.claritas.ParseRequest\x1a\x13.claritas.DataChunk0\x01B\aZ\x05./apib\x06proto3"

var (
	file_claritas_proto_rawDescOnce sync.Once
	file_claritas_proto_rawDescData []byte
)

func file_claritas_proto_rawDescGZIP() []byte {
	file_claritas_proto_rawDescOnce.Do(func() {
		file_claritas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_claritas_proto_rawDesc), len(file_claritas_proto_rawDesc)))
	})
	return file_claritas_proto_rawDescData
}

var file_claritas_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_claritas_proto_goTypes = []any{
	(*Empty)(nil),           // 0: claritas.Empty
	(*HealthStatus)(nil),    // 1: claritas.HealthStatus
	(*FileRequest)(nil),     // 2: claritas.FileRequest
	(*HeadersResponse)(nil), // 3: claritas.HeadersResponse
	(*ParseRequest)(nil),    // 4: claritas.ParseRequest
	(*DataChunk)(nil),       // 5: claritas.DataChunk
}
var file_claritas_proto_depIdxs = []int32{
	0, // 0: claritas.ClaritasEngine.Ping:input_type -> claritas.Empty
	2, // 1: claritas.ClaritasEngine.GetHeaders:input_type -> claritas.FileRequest
	4, // 2: claritas.ClaritasEngine.StreamData:input_type -> claritas.ParseRequest
	1, // 3: claritas.ClaritasEngine.Ping:output_type -> claritas.HealthStatus
	3, // 4: claritas.ClaritasEngine.GetHeaders:output_type -> claritas.HeadersResponse
	5, // 5: claritas.ClaritasEngine.StreamData:output_type -> claritas.DataChunk
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_claritas_proto_init() }
func file_claritas_proto_init() {
	if File_claritas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_claritas_proto_rawDesc), len(file_claritas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_claritas_proto_goTypes,
		DependencyIndexes: file_claritas_proto_depIdxs,
		MessageInfos:      file_claritas_proto_msgTypes,
	}.Build()
	File_claritas_proto = out.File
	file_claritas_proto_goTypes = nil
	file_claritas_proto_depIdxs = nil
}
