// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: claritas.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClaritasEngine_Ping_FullMethodName       = "/claritas.ClaritasEngine/Ping"
	ClaritasEngine_GetHeaders_FullMethodName = "/claritas.ClaritasEngine/GetHeaders"
	ClaritasEngine_StreamData_FullMethodName = "/claritas.ClaritasEngine/StreamData"
)

// ClaritasEngineClient is the client API for ClaritasEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClaritasEngineClient interface {
	// Checks if the Go backend is alive
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error)
	// Reads the first line of the CSV and returns column names
	GetHeaders(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*HeadersResponse, error)
	// Reads the CSV and streams parsed data points back to the client
	StreamData(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error)
}

type claritasEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewClaritasEngineClient(cc grpc.ClientConnInterface) ClaritasEngineClient {
	return &claritasEngineClient{cc}
}

func (c *claritasEngineClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthStatus)
	err := c.cc.Invoke(ctx, ClaritasEngine_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *claritasEngineClient) GetHeaders(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*HeadersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeadersResponse)
	err := c.cc.Invoke(ctx, ClaritasEngine_GetHeaders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *claritasEngineClient) StreamData(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClaritasEngine_ServiceDesc.Streams[0], ClaritasEngine_StreamData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ParseRequest, DataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClaritasEngine_StreamDataClient = grpc.ServerStreamingClient[DataChunk]

// ClaritasEngineServer is the server API for ClaritasEngine service.
// All implementations must embed UnimplementedClaritasEngineServer
// for forward compatibility.
type ClaritasEngineServer interface {
	// Checks if the Go backend is alive
	Ping(context.Context, *Empty) (*HealthStatus, error)
	// Reads the first line of the CSV and returns column names
	GetHeaders(context.Context, *FileRequest) (*HeadersResponse, error)
	// Reads the CSV and streams parsed data points back to the client
	StreamData(*ParseRequest, grpc.ServerStreamingServer[DataChunk]) error
	mustEmbedUnimplementedClaritasEngineServer()
}

// UnimplementedClaritasEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClaritasEngineServer struct{}

func (UnimplementedClaritasEngineServer) Ping(context.Context, *Empty) (*HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedClaritasEngineServer) GetHeaders(context.Context, *FileRequest) (*HeadersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHeaders not implemented")
}
func (UnimplementedClaritasEngineServer) StreamData(*ParseRequest, grpc.ServerStreamingServer[DataChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamData not implemented")
}
func (UnimplementedClaritasEngineServer) mustEmbedUnimplementedClaritasEngineServer() {}
func (UnimplementedClaritasEngineServer) testEmbeddedByValue()                        {}

// UnsafeClaritasEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClaritasEngineServer will
// result in compilation errors.
type UnsafeClaritasEngineServer interface {
	mustEmbedUnimplementedClaritasEngineServer()
}

func RegisterClaritasEngineServer(s grpc.ServiceRegistrar, srv ClaritasEngineServer) {
	// If the following call panics, it indicates UnimplementedClaritasEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClaritasEngine_ServiceDesc, srv)
}

func _ClaritasEngine_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClaritasEngineServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClaritasEngine_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClaritasEngineServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClaritasEngine_GetHeaders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClaritasEngineServer).GetHeaders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClaritasEngine_GetHeaders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClaritasEngineServer).GetHeaders(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClaritasEngine_StreamData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ParseRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClaritasEngineServer).StreamData(m, &grpc.GenericServerStream[ParseRequest, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClaritasEngine_StreamDataServer = grpc.ServerStreamingServer[DataChunk]

// ClaritasEngine_ServiceDesc is the grpc.ServiceDesc for ClaritasEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClaritasEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "claritas.ClaritasEngine",
	HandlerType: (*ClaritasEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ClaritasEngine_Ping_Handler,
		},
		{
			MethodName: "GetHeaders",
			Handler:    _ClaritasEngine_GetHeaders_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamData",
			Handler:       _ClaritasEngine_StreamData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "claritas.proto",
}
