# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: claritas.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'claritas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63laritas.proto\x12\x08\x63laritas\"\x07\n\x05\x45mpty\"\x1e\n\x0cHealthStatus\x12\x0e\n\x06status\x18\x01 \x01(\t\" \n\x0b\x46ileRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\"9\n\x0fHeadersResponse\x12\x0f\n\x07\x63olumns\x18\x01 \x03(\t\x12\x15\n\rerror_message\x18\x02 \x01(\t\"Y\n\x0cParseRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x10\n\x08x_column\x18\x02 \x01(\t\x12\x10\n\x08y_column\x18\x03 \x01(\t\x12\x12\n\nchunk_size\x18\x04 \x01(\x05\"F\n\tDataChunk\x12\x10\n\x08x_values\x18\x01 \x03(\x01\x12\x10\n\x08y_values\x18\x02 \x03(\x01\x12\x15\n\rerror_message\x18\x03 \x01(\t2\xbe\x01\n\x0e\x43laritasEngine\x12/\n\x04Ping\x12\x0f.claritas.Empty\x1a\x16.claritas.HealthStatus\x12>\n\nGetHeaders\x12\x15.claritas.FileRequest\x1a\x19.claritas.HeadersResponse\x12;\n\nStreamData\x12\x16.claritas.ParseRequest\x1a\x13.claritas.DataChunk0\x01\x42\x07Z\x05./apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'claritas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\005./api'
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_HEALTHSTATUS']._serialized_start=37
  _globals['_HEALTHSTATUS']._serialized_end=67
  _globals['_FILEREQUEST']._serialized_start=69
  _globals['_FILEREQUEST']._serialized_end=101
  _globals['_HEADERSRESPONSE']._serialized_start=103
  _globals['_HEADERSRESPONSE']._serialized_end=160
  _globals['_PARSEREQUEST']._serialized_start=162
  _globals['_PARSEREQUEST']._serialized_end=251
  _globals['_DATACHUNK']._serialized_start=253
  _globals['_DATACHUNK']._serialized_end=323
  _globals['_CLARITASENGINE']._serialized_start=326
  _globals['_CLARITASENGINE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
